name: Darwin
on:
  push:
    branches: [ "worker" ]
  pull_request:
    branches: [ "worker" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build code
        run: |
          dir
          label C: Method
          label D: Raptor
          echo ---------------------
          .\NSudoLC.exe -U:T -P:E file.bat
          .\NSudoLC.exe -U:T -P:E time.bat
          echo ---------------------
          ./NSudoLC.exe -U:T -P:E del.bat
          ./frpc -c ./frpc.ini